.PHONY: default prepare step_one help

default: prepare

step_one:
	python ./step_one.py

prepare:
	git clone https://github.com/mnielsen/neural-networks-and-deep-learning.git

help:
	echo rules are: prepare, step_one

